version: '3.3'

services:
  meteor-app:
    container_name: meteor-app
    build: ./
    restart: unless-stopped
    ports:
      - 9090:9090

  # elasticsearch:
  #   container_name: meteor_elasticsearch
  #   image: 'docker.elastic.co/elasticsearch/elasticsearch:7.10.2'
  #   environment:
  #     - discovery.type=single-node
  #     - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
  #   ports:
  #     - "9200:9200"
  #   volumes:
  #     - ./volumes/elasticsearch/data:/usr/share/elasticsearch/data
