version: '3.3'

services:
  meteor-app:
    container_name: meteor-app
    build: ./
    restart: unless-stopped
    ports:
      - 9090:9090

  # elasticsearch:
  #   container_name: elasticsearch
  #   image: 'docker.elastic.co/elasticsearch/elasticsearch:7.10.2'
  #   environment:
  #     - discovery.type=single-node
  #     - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
  #   ports:
  #     - "9200:9200"
  #   volumes:
  #     - ./volumes/elasticsearch/data:/usr/share/elasticsearch/data
  
  # logstash:
  #   build:
  #     context: logstash
  #   env_file: .env
  #   volumes:
  #     - ./logstash/config/pipelines.yml:/usr/share/logstash/config/pipelines.yml
  #     - ./logstash/pipelines/:/usr/share/logstash/pipeline/
  #     - ./logstash/queries/:/usr/share/logstash/config/queries/
  #   depends_on:
  #     - elasticsearch

  # kibana:
  #   image: 'docker.elastic.co/kibana/kibana:7.10.2'
  #   ports:
  #     - "5601:5601"
  #   hostname: kibana
  #   depends_on:
  #     - elasticsearch
